"""empty message

Revision ID: 3cbe33bf27f1
Revises: 1eee8bd1d8c8
Create Date: 2024-02-08 20:43:57.565496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbe33bf27f1'
down_revision = '1eee8bd1d8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.String(length=80), nullable=False))
        batch_op.create_foreign_key('user_profile', 'users_profiles', ['profile'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
