"""empty message

Revision ID: 4f02e548211b
Revises: 2ec64fd5b324
Create Date: 2024-02-14 22:12:28.700136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f02e548211b'
down_revision = '2ec64fd5b324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_borrowing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('genreId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_borrowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genreId', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(None, 'genre', ['genreId'], ['id'])

    # ### end Alembic commands ###
