"""empty message

Revision ID: 703f0da836aa
Revises: 8d894091242d
Create Date: 2024-02-06 20:37:20.923847

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '703f0da836aa'
down_revision = '8d894091242d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registerDate', sa.Date(), nullable=False, server_default=str(datetime.today())))
        batch_op.add_column(sa.Column('registerDate2', sa.Date(), nullable=False, server_default=str(datetime.today())))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registerDate2')
        batch_op.drop_column('registerDate')

    # ### end Alembic commands ###
