"""empty message

Revision ID: a7963cb946e5
Revises: 703f0da836aa
Create Date: 2024-02-07 20:49:54.242075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7963cb946e5'
down_revision = '703f0da836aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registerDate2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registerDate2', sa.DATE(), server_default=sa.text("'2024-02-06 20:39:42.702775'"), nullable=False))

    # ### end Alembic commands ###
