"""empty message

Revision ID: c847ede85fdb
Revises: 1e495b0573b8
Create Date: 2024-02-19 14:04:13.771150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c847ede85fdb'
down_revision = '1e495b0573b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_borrowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genreId', sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_book_borrowing_genreId_genre'), 'genre', ['genreId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_borrowing', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_book_borrowing_genreId_genre'), type_='foreignkey')
        batch_op.drop_column('genreId')

    # ### end Alembic commands ###
