"""empty message

Revision ID: d06748a42f1b
Revises: c847ede85fdb
Create Date: 2024-02-19 14:06:13.937744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06748a42f1b'
down_revision = 'c847ede85fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_borrowing', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_borrowing_genreId_genre', type_='foreignkey')
        batch_op.drop_column('genreId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_borrowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genreId', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_book_borrowing_genreId_genre', 'genre', ['genreId'], ['id'])

    # ### end Alembic commands ###
